### ISSUE TITLE
Autocomplete list instantly closes before selection & sometimes stays open in the DOM after selection

### ISSUE THREAD

**Issue by GiridharRNair** [anubra266/choc-autocomplete#280]
https://github.com/user-attachments/assets/3b0e1854-b8a6-4599-9521-5eb8d893c942

The Autocomplete list occasionally closes instantly before a selection can be made. Additionally, the Autocomplete list remains in the DOM even after it has visually closed.

While I couldn’t capture the Autocomplete list staying in the DOM after close, it seems related to [this popover issue](https://github.com/chakra-ui/chakra-ui/issues/7647) in Chakra UI. 

Below is the full code for the Autocomplete input shown in the video:

```javascript
import { useState, useMemo } from "react";
import { AutoComplete, AutoCompleteInput, AutoCompleteItem, AutoCompleteList } from "@choc-ui/chakra-autocomplete";
import { VStack, Tooltip, Spinner, InputGroup, InputRightElement, CloseButton } from "@chakra-ui/react";
import { RepeatClockIcon } from "@chakra-ui/icons";
import PropTypes from "prop-types";
import _debounce from "lodash/debounce";
import axios from "axios";

const DEFAULT_TEACHER_SUGGESTIONS = ["John Cole", "Regina Ybarra", "Stephanie Taylor", "Bentley Garrett", "Karl Sengupta"];
const DEFAULT_COURSE_SUGGESTIONS = ["CS 2305", "MATH 2418", "CHEM 2401", "ACCT 6305", "SPAN 2311"];

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:80";

function Inputs({ setProfessor, setCourse, professor, course, isCompareInputs = false }) {
    const PROFESSOR_STORAGE_KEY = `LastQueries${isCompareInputs ? "Compare" : ""}Professor`;
    const COURSE_STORAGE_KEY = `LastQueries${isCompareInputs ? "Compare" : ""}Course`;

    const [professorLoading, setProfessorLoading] = useState(false);
    const [courseLoading, setCourseLoading] = useState(false);
    const [professorSuggestions, setProfessorSuggestions] = useState(JSON.parse(localStorage.getItem(PROFESSOR_STORAGE_KEY)) || DEFAULT_TEACHER_SUGGESTIONS);
    const [courseSuggestions, setCourseSuggestions] = useState(JSON.parse(localStorage.getItem(COURSE_STORAGE_KEY)) || DEFAULT_COURSE_SUGGESTIONS);

    const getLastQueriedProfessors = () => JSON.parse(localStorage.getItem(PROFESSOR_STORAGE_KEY)) || DEFAULT_TEACHER_SUGGESTIONS;
    const getLastQueriedCourses = () => JSON.parse(localStorage.getItem(COURSE_STORAGE_KEY)) || DEFAULT_COURSE_SUGGESTIONS;

    const fetchSuggestions = useMemo(
        () =>
            _debounce(async (professorParam, courseParam) => {
                try {
                    professorParam = professorParam.trim();
                    courseParam = courseParam.trim();
                    if (!professorParam && !courseParam) {
                        return;
                    }

                    const { data } = await axios.get(`${API_URL}/suggestions?teacher=${professorParam}&course=${courseParam}`);

                    setProfessorSuggestions(data.professors);
                    setCourseSuggestions(data.courses);
                } catch (error) {
                    console.error(error.response?.data.detail);
                } finally {
                    setProfessorLoading(false);
                    setCourseLoading(false);
                }
            }, 250),
        [],
    );

    return (
        <VStack width={325}>
            <AutoComplete
                openOnFocus
                disableFilter={true}
                suggestWhenEmpty={true}
                freeSolo={true}
                isLoading={professorLoading}
                emptyState="Professor not found"
                onSelectOption={({ item }) => {
                    setProfessor(item.label);
                    fetchSuggestions(item.label, course);
                }}
            >
                <InputGroup>
                    <Tooltip placement="top" label="Ignore prefixes, suffixes, and middle names" fontSize={"xs"}>
                        <AutoCompleteInput
                            height={8}
                            placeholder="Enter Teacher Name"
                            value={professor}
                            loadingIcon={<Spinner size={"xs"} mb={2} />}
                            onChange={(e) => {
                                setProfessorLoading(true);
                                setProfessor(e.target.value);
                                fetchSuggestions(e.target.value, course);
                            }}
                        />
                    </Tooltip>
                    <InputRightElement>
                        {!professorLoading && professor && (
                            <CloseButton
                                size="sm"
                                mb={2}
                                onClick={() => {
                                    setProfessor("");
                                    setProfessorSuggestions(getLastQueriedProfessors());
                                    setCourseSuggestions(getLastQueriedCourses());
                                }}
                            />
                        )}
                    </InputRightElement>
                </InputGroup>
                {!professorLoading && (
                    <AutoCompleteList fontSize="sm">
                        {(professor.trim() ? professorSuggestions : getLastQueriedProfessors()).map((professorOption, index) => (
                            <AutoCompleteItem value={professorOption} key={index} justify="space-between" align="center">
                                {professorOption}
                                {!professor.trim() && JSON.stringify(getLastQueriedProfessors()) !== JSON.stringify(DEFAULT_TEACHER_SUGGESTIONS) && (
                                    <RepeatClockIcon />
                                )}
                            </AutoCompleteItem>
                        ))}
                    </AutoCompleteList>
                )}
            </AutoComplete>

            <AutoComplete
                openOnFocus
                disableFilter={true}
                suggestWhenEmpty={true}
                freeSolo={true}
                isLoading={courseLoading}
                emptyState={`Course(s) not found ${professor ? `for ${professor}` : ""}`}
                onSelectOption={({ item }) => setCourse(item.label)}
            >
                <InputGroup>
                    <AutoCompleteInput
                        height={8}
                        placeholder={"Enter Course"}
                        value={course}
                        loadingIcon={<Spinner size={"xs"} mb={2} />}
                        onChange={(e) => {
                            setCourseLoading(true);
                            setCourse(e.target.value);
                            fetchSuggestions(professor, e.target.value);
                        }}
                    />
                    <InputRightElement>
                        {!courseLoading && course && (
                            <CloseButton
                                size="sm"
                                mb={2}
                                onClick={() => {
                                    setCourse("");
                                    professor ? fetchSuggestions(professor, "") : setCourseSuggestions(getLastQueriedCourses());
                                }}
                            />
                        )}
                    </InputRightElement>
                </InputGroup>
                {!courseLoading && (
                    <AutoCompleteList style={{ maxHeight: "230px", overflowY: "auto" }} fontSize="sm">
                        {(course.trim() || professor.trim() ? courseSuggestions : getLastQueriedCourses()).map((courseOption, index) => (
                            <AutoCompleteItem value={courseOption} key={index} justify="space-between" align="center">
                                {courseOption}
                                {!course.trim() && !professor.trim() && JSON.stringify(getLastQueriedCourses()) !== JSON.stringify(DEFAULT_COURSE_SUGGESTIONS) && (
                                    <RepeatClockIcon />
                                )}
                            </AutoCompleteItem>
                        ))}
                    </AutoCompleteList>
                )}
            </AutoComplete>
        </VStack>
    );
}

Inputs.propTypes = {
    setProfessor: PropTypes.func.isRequired,
    setCourse: PropTypes.func.isRequired,
    professor: PropTypes.string.isRequired,
    course: PropTypes.string.isRequired,
    isCompareInputs: PropTypes.bool,
};

export default Inputs;
```

Here is the full repo if interested: https://github.com/GiridharRNair/ProfStatsUTD. The autocomplete input is found in `src/inputs.jsx`.

Expected Behavior
The Autocomplete list should remain open until the user makes a selection or clicks away.
The Autocomplete list should be fully removed from the DOM after the Autocomplete is closed.

Thanks for the great work on this component regardless!

**Comment by Kysluss** [comment]
@GiridharRNair 

I remember dealing with this issue before and can't remember how I resolved it.  I'm going to take a look and see what I can figure out.

**Comment by Kysluss** [comment]
@GiridharRNair 

I was able to reproduce this even without any conditional rendering.  The linked issue on Chakra UI page says to add `key={Math.random()}` to the `Popover` component but doing so causes the `AutoCompleteInput` to not be focusable.

This sounds odd, but I was able to fix this by not passing the `onOpen` and `onClose` props to the `Popover`.  Can you try v5.7.3 that I just pushed up?  If that works, I will finalize the release on github.

**Comment by Kysluss** [comment]
Sorry I'm not sure how my v5 branch got behind.  v5.8.1 also published with the same fix.

**Comment by GiridharRNair** [comment]
Works beautifully, thank you for your work!

**Comment by GiridharRNair** [comment]
https://github.com/user-attachments/assets/9a37fe30-37a7-423b-b07f-12968925108d


The issue where the popover remains open after clicking away from the input still persists. However, this behavior occurs only when no input is selected, and dummy values are left in the field.

**Comment by Kysluss** [comment]
For some reason, I am not able to reproduce this while using local data.  I am wondering if it has something to do with the loading state.  I'll keep trying to reproduce it to see what's going on there.

One thing to try in the meantime is `listAllValuesOnFocus={true}`.  It didn't make a difference locally but it does factor into the show/hide logic.

**Comment by Kysluss** [comment]
@GiridharRNair I made the below simplified example that I think mimics how you were using it.  From the video you posted, it looks like the issue is the when you try to open the second, dependent list right?  For some reason, I wasn't able to reproduce it.

```js
import {
  Flex,
  FormControl,
} from "@chakra-ui/react";
import * as React from "react";
import { useState } from "react";
import {
  AutoComplete,
  AutoCompleteInput,
  AutoCompleteItem,
  AutoCompleteList,
} from "../../src/index";

const options = [
  { label: "apple", value: "one" },
  { label: "appoint", value: "two" },
  { label: "zap", value: "three" },
  { label: "cap", value: "four" },
  { label: "japan", value: "five" },
];

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

const fetchData = (term: string) => sleep(500)
  .then(() => options.filter(o => 
      o.value.indexOf(term) !== -1 || o.label.indexOf(term) !== -1
  ))

function App() {
  const [isLoading, setIsLoading] = useState(false);
  const [localOptions, setLocalOptions] = useState(options);
  const [otherOptions, setOtherOptions] = useState(options);

  const onSearchHandler = React.useCallback((term: string) => {
    setIsLoading(true);

    fetchData(term)
      .then(newOptions => {
        setLocalOptions(newOptions);
        setIsLoading(false);
        setOtherOptions([...options]);
      })
  }, [setIsLoading, setLocalOptions]);

  return (
    <Flex pt="48" justify="center" align="center" w="full">
      <FormControl id="email" w="60">
        <AutoComplete
          openOnFocus 
          suggestWhenEmpty 
          freeSolo
          isLoading={isLoading}
          emptyState={"No values found"} 
        >
          <AutoCompleteInput variant="filled" w="48" onChange={e => onSearchHandler(e.target.value)} placeholder="API-Based List" />
          { !isLoading && <AutoCompleteList>
              {localOptions.map(option => (
                <AutoCompleteItem
                  key={`option-${option.value}`}
                  value={{ title: `${option.value}` }}
                  // getValue={a => a.title}
                  label={option.label}
                  textTransform="capitalize"
                />
              ))}
          </AutoCompleteList> }
        </AutoComplete>
        <AutoComplete
          openOnFocus 
          suggestWhenEmpty 
          freeSolo
          emptyState={"No values found"}
        >
          <AutoCompleteInput variant="filled" w="48" placeholder="Dependent List" />
          <AutoCompleteList>
              {otherOptions.map(option => (
                <AutoCompleteItem
                  key={`option-${option.value}`}
                  value={{ title: `${option.value}` }}
                  // getValue={a => a.title}
                  label={option.label}
                  textTransform="capitalize"
                />
              ))}
          </AutoCompleteList>
        </AutoComplete>
      </FormControl>
    </Flex>
  );
}

export default App;
```

**Comment by Kysluss** [comment]
@GiridharRNair I wanted to follow up on this to see if you were able to provide a different setup that reproduced the issue.

**Comment by GiridharRNair** [comment]
Apologies for the delayed response. I wasn’t able to create a simplified setup that reproduces the issue, but I haven’t received any further reports about it. I appreciate you taking the time to look into it!

**Comment by Kysluss** [comment]
No problem.  I'll close this again, but feel free to open another issue if you notice again.  [v5.8.2](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.8.2) just came out that fixes an issue with `multiple` and `creatable` in case you're using that combo as well.
